apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: v1
kind: Pod
metadata:
  name: counter-pod
spec:
  containers:
  - name: counter-container
    image: us-central1-docker.pkg.dev/peteryizhong-gke-dev/peteryizhong-repository/counter:latest
    volumeMounts:
    - name: counter-storage
      mountPath: /data
  volumes:
  - name: counter-storage
    persistentVolumeClaim:
      claimName: counter-storage-claim